name: shopizer CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container: shopizerecomm/ci:java11
    steps:
      - name: Checkout code
        uses: actions/checkout@v4      
      - name: TEST Build
        run: echo "shopizer build and test"
          set -x
          /home/shopizer/tools/shopizer.sh tests

