name: shopizer CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: shopizerecomm/ci:java11
      volumes: 
        - ~/.m2:~/.m2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-maven-${{ hashFiles('/__w/shopizer/shopizer/pom.xml') }}
      - name: TEST Build
        run: /home/shopizer/tools/shopizer.sh tests

